# Crear el archivo netlify.toml correcto
$netlifyContent = @"
[build]
  command = "npm run build"
  publish = "build"
  base = "frontend"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://your-backend-url.onrender.com"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://your-backend-staging-url.onrender.com"
"@

$netlifyContent | Out-File -FilePath "netlify.toml" -Encoding utf8